insult_custom replace
KODEX-Mods/ElderKings-Deutsch pull request #10
Opened 2023-08-25 21:29 UTC by xzudemimino

2023-08-26 11:24 UTC, TheynT requested changes

2023-08-26 11:24 UTC, TheynT commented on localization/replace/german/customizable_localization/insult_custom_loc_l_german.yml
> + cold_hearted_behavior:0 "Kaltherzigkeit"
Line 77 bis 91, hier nicht die Subjekte sondern Adjektive:
cold-heartedness -> kaltherziges
weil Behaviour -> Verhalten

2023-08-26 11:39 UTC, Dillo234 commented on localization/replace/german/customizable_localization/insult_custom_loc_l_german.yml
> + cold_hearted_behavior:0 "Kaltherzigkeit"
Woher nimmst du an, die Wörter hingen mit ...Verhalten zusammen? Aus meiner Sicht sind Substantive da richtig. "_behavior" ist ja nur Bestandteil des Keys

2023-08-27 15:15 UTC, Dillo234 approved these changes

2023-08-30 11:37 UTC, merged